### ISSUE TITLE
Document expected metrics forwarder API format

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/java-buildpack-metric-writer#1]
Readme.md [specifies](https://github.com/cloudfoundry/java-buildpack-metric-writer/blob/master/README.md#cloud-foundry-spring-boot-metric-writer)  that the metrics writer: 

> writes metric updates to a Metron endpoint

However, the metron endpoint only supports UDP and GRPC endpoints (according to [doc](https://github.com/cloudfoundry/loggregator/blob/develop/docs/metron.md) and [tests](https://github.com/cloudfoundry/loggregator/blob/develop/src/code.cloudfoundry.org/loggregator/metron/component_tests/metron_test.go)).

The [metrics writer tests](https://github.com/cloudfoundry/java-buildpack-metric-writer/blob/master/src/test/java/org/cloudfoundry/metrics/CloudFoundryMetricsExporterTest.java#L229-L256) seem to assume the remote endpoint accepts HTTP JSON endpoints.

Is the metrics writer using metron agent GRPC with protocol buffer 3 [builtin json mapping support](https://developers.google.com/protocol-buffers/docs/proto3#json) ? However, [grpc specs](https://grpc.io/docs/guides/wire.html) specify in this case a content type `application/grpc+json` whereas the metrics writer writes a `application/json;charset=UTF-8` content type. In addition, the content of the JSON formatted payload does not seem to match the metron agent V2 [envelope format](https://github.com/cloudfoundry/loggregator-api/blob/master/README.md) documented by the [loggregator api](https://github.com/cloudfoundry/loggregator#loggregator-api) and implemented in [protocol buffer files](https://github.com/cloudfoundry/loggregator-api/blob/master/v2/envelope.proto)

Is it instead that the metric writer assumes a distinct metrics forwarder service API from Metron agent ? Java buildpack [metrics writer doc](https://github.com/cloudfoundry/java-buildpack/blob/05b7eb57788d6f8330129d17b7b69237ecde73f9/docs/framework-metric_writer.md) mentions a `Metrics Forwarder Service` and not metron agent. 

If so, is the metrics forwarder service implementation open source ?
Is there plans in the future to directly write to metron agent leveraging official API ?

**Comment by nebhale** [comment]
Yep, that reference is an artifact one of the many incarnations this project went through.  I'll update the docs to be accurate, but it's working against a PCF-specific service that translates from a REST API to the firehose internally.  As [discussed here](https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/thread/TZTZZF4PRZF36NUUBHPQMQUHEURANRQS/), this is a PCF-specific feature to bridge the gap to an OSS delivery of the same functionality.

**Comment by gberche-orange** [comment]
Sorry I missed this cf-dev@ thread. Thanks @nebhale for your response and pointing me to it!

**Comment by nebhale** [comment]
@gberche-orange No worries.  This addition was done pretty quietly to satisfy a particular customer before the OSS would be ready.
