### ISSUE TITLE
Support Spring Boot 2 / Micrometer

### ISSUE THREAD

**Issue by making** [cloudfoundry/java-buildpack-metric-writer#2]
`org.springframework.boot.actuate.endpoint.PublicMetrics` does not exist in Spring Boot 2. So, `CloudFoundryMetricsAutoConfiguration` isn't enabled for Spring Boot 2. 

Do you have any plan to support Spring Boot 2 / Micrometer?

**Comment by nebhale** [comment]
We absolutely do.  It’s on my list of things to get done before Spring Boot 2’s GA release, but I’m not sure about whether it’ll get done before Micrometer’s GA release.

**Comment by slu-it** [comment]
@nebhale any info on the timeline of this? Spring Boot is now GA

**Comment by nebhale** [comment]
Sorry, never got closed out but went out with Java Buildpack 4.8.  Please note that this only takes care of the part where the metrics are put onto Loggregator.  Consumers of those metrics may not be able to properly interpret the multi-dimensional metric structure.
